### ISSUE TITLE
Inconsistent connectivity

### ISSUE THREAD

**Issue by gioargyr** [big-data-europe/README#3]
Hi! I ran Geotriples and Strabon in all nodes of the cluster. They need to run in the same node in order to mount the same dir and share files. Connectivity between them is perfect in nodes master, slave1 and slave2, but is bad in slave3 and slave4!
I attach the compose file I use for them. As you can see, I use "affinity" to make sure geotriples and strabon are going to run in the same node. Don't mind about postgis, it's just the db and works fine in any node.
Also, attached you can find the error I get in slaves 3 and 4.
Have you seen anything like this before?
Do you have any idea what causes this inconsistency?
[docker-compose.txt](https://github.com/big-data-europe/README/files/444261/docker-compose.txt)
[slave3-4.txt](https://github.com/big-data-europe/README/files/444262/slave3-4.txt)

**Comment by gmouchakis** [comment]
This seems like a application related issue. Does this happen each time you try to run gioargyr/geotriples-ws:2.4.0 in slave3 or slave4? Could it be that you are missing a dependency in your docker or using different docker images in slave3 and slave4?

**Comment by gioargyr** [comment]
Hi! I just did another test. At first I ran strabon and geotriples at slave2. I triggered geotriples and communicated succesfuly with strabon. I stopped and removed the containers and then I ran strabon and geotriples at slave3. I triggered geotriples and returned an error. So it cannot connect with strabon.
I am able to run the pilot using "constraint:node!=/slave[34]/" in strabon and geotriples just follows. I just find the bug very strange.

**Comment by gmouchakis** [comment]
Can you please tell me how to trigger geotriples so I can reproduce this?

**Comment by gioargyr** [comment]
Yes of course.
In the master node there is a /home/iitadmin/curl-test_files dir with the usefull .json files. After you ran the dockers run:
$ curl -X POST -d @path_to_json/post_geo.json http://<ip_of_geotriples>:8192/geotriples/event -H "Content-Type:application/json" -H "Accept: application/json"
or/and
$ curl -X POST -d @path_to_json/changes.json http://<ip_of_geotriples>:8192/geotriples/changes -H "Content-Type:application/json" -H "Accept: application/json"

**Comment by gmouchakis** [comment]
When I try it I get the same error as you but I'm not sure yet what causes it. It seems that there is a library missing but I don't know why the error does not occur on every machine. The containers seem able to communicate with each other.

Could it be that each machine has different /home/iitadmin/SC7Pilot/geostrabon directories? I can see some differences but I don't know if that's the cause.

Also when deploying on slave2, after geotriples is triggered the log ends with "Status code 500". Is this an error?

**Comment by gmouchakis** [comment]
@gioargyr 
was this fixed with the update and fresh install of docker swarm?

**Comment by gioargyr** [comment]
Hi! I tested again geotriples-strabon communication and the problem remains exactly the same!
Also, I have the exactly same problem from sextant to event-store. Sextant is always running in slave1, but it can connect to event-store only when the event-store is running in slaves 1 & 2!

**Comment by gioargyr** [comment]
After updating the infrastructure (January 2017), the problem dissapeared! Now I have consistent connectivity in every node.
